//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViennaNET.Word.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViennaNET.Word.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pkg:package xmlns:pkg=&quot;http://schemas.microsoft.com/office/2006/xmlPackage&quot;&gt;
        ///&lt;pkg:part pkg:name=&quot;/_rels/.rels&quot; pkg:contentType=&quot;application/vnd.openxmlformats-package.relationships+xml&quot; pkg:padding=&quot;512&quot;&gt;
        ///&lt;pkg:xmlData&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///&lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties&quot; Target=&quot;docProps/app.xml&quot;/&gt;
        ///&lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookmarkTestDocument {
            get {
                return ResourceManager.GetString("BookmarkTestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pkg:package xmlns:pkg=&quot;http://schemas.microsoft.com/office/2006/xmlPackage&quot;&gt;
        ///&lt;pkg:part pkg:name=&quot;/_rels/.rels&quot; pkg:contentType=&quot;application/vnd.openxmlformats-package.relationships+xml&quot; pkg:padding=&quot;512&quot;&gt;
        ///&lt;pkg:xmlData&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///&lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties&quot; Target=&quot;docProps/app.xml&quot;/&gt;
        ///&lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckboxTestDocument {
            get {
                return ResourceManager.GetString("CheckboxTestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pkg:package xmlns:pkg=&quot;http://schemas.microsoft.com/office/2006/xmlPackage&quot;&gt;
        ///&lt;pkg:part pkg:name=&quot;/_rels/.rels&quot; pkg:contentType=&quot;application/vnd.openxmlformats-package.relationships+xml&quot; pkg:padding=&quot;512&quot;&gt;
        ///&lt;pkg:xmlData&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///&lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties&quot; Target=&quot;docProps/app.xml&quot;/&gt;
        ///&lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DateTestDocument {
            get {
                return ResourceManager.GetString("DateTestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pkg:package xmlns:pkg=&quot;http://schemas.microsoft.com/office/2006/xmlPackage&quot;&gt;
        ///&lt;pkg:part pkg:name=&quot;/_rels/.rels&quot; pkg:contentType=&quot;application/vnd.openxmlformats-package.relationships+xml&quot; pkg:padding=&quot;512&quot;&gt;
        ///&lt;pkg:xmlData&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///&lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties&quot; Target=&quot;docProps/app.xml&quot;/&gt;
        ///&lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImageTestDocument {
            get {
                return ResourceManager.GetString("ImageTestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pkg:package xmlns:pkg=&quot;http://schemas.microsoft.com/office/2006/xmlPackage&quot;&gt;
        ///&lt;pkg:part pkg:name=&quot;/_rels/.rels&quot; pkg:contentType=&quot;application/vnd.openxmlformats-package.relationships+xml&quot; pkg:padding=&quot;512&quot;&gt;
        ///&lt;pkg:xmlData&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///&lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties&quot; Target=&quot;docProps/app.xml&quot;/&gt;
        ///&lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RichTextTestDocument {
            get {
                return ResourceManager.GetString("RichTextTestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pkg:package xmlns:pkg=&quot;http://schemas.microsoft.com/office/2006/xmlPackage&quot;&gt;
        ///&lt;pkg:part pkg:name=&quot;/_rels/.rels&quot; pkg:contentType=&quot;application/vnd.openxmlformats-package.relationships+xml&quot; pkg:padding=&quot;512&quot;&gt;
        ///&lt;pkg:xmlData&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///&lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties&quot; Target=&quot;docProps/app.xml&quot;/&gt;
        ///&lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableTestDocument {
            get {
                return ResourceManager.GetString("TableTestDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAhAAAAAoCAYAAACvtsNgAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAABJfSURBVHherY5BqiUxDMTe/S/9ZyXwiIiY0AIvSlVp+vf3Mb/f778DZyhv2HlvzxXuK9tDeeMduc68+jpwhvLgnmxvqrcn2xe1u/k6cDbb3jtnM9+cDm65qB3efWV7KG+8I9ub196ebF/Ubn7jdOAMW0+2L7ybb+fBqZsH5aH68uCeM9seagf02x3UvjzQ1+7Wg3ccVLb/is+/WD/sDOUNO+/tucJ9ZXsob7wj15lXXwfOUB7ck+1N9fZk+6J2N18Hzmbbe+ds5pvTwS0XtcO7r2wP5Y13ZHvz2tuT7YvazW+cDpxh68n2hXfz7Tw4dfOgPFRfHtxzZttD7YB+u4Palwf62t168I6DyvZf8fkX64edobxh5709V7ivbA/ljXfkOvPq68AZyoN7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestImageData {
            get {
                return ResourceManager.GetString("TestImageData", resourceCulture);
            }
        }
    }
}
